// -- ./src/template/svg/index.js
export { default as VerticalSvg } from './layout/Vertical'
export { default as HorizontalSvg } from './layout/Horizontal'
export { default as SemiBoxSvg } from './layout/Semibox'

//  dual tone icon

export { default as DSearch } from './duel-tone/Dsearch'
export { default as Session } from './home/Session'
export { default as Eye } from './home/Eye'
export { default as Increase } from './home/Increase'
export { default as Cup } from './home/Cup'
export { default as CupBar } from './home/CupBar'
export { default as NoteIcon } from './home/Note'
export { default as Users } from './home/Users'
export { default as Counter } from './home/Counter'
export { default as Docs } from './home/Docs'
export { default as CheckShape } from './home/CheckShape'
export { default as DocsCheck } from './duel-tone/DocsCheck'
export { default as DocsArrow } from './duel-tone/DocsArrow'
export { default as Spam } from './home/Spam'
export { default as Stacks } from './home/Stack'
export { default as CheckMark } from './home/CheckMark'
export { default as Alert2 } from './home/Alert'
export { default as Crown } from './home/Crown'
export { default as Cup1 } from './duel-tone/Cup'
export { default as Bell } from './duel-tone/Bell'
export { default as ColorPalate } from './duel-tone/ColorPalater'
export { default as ChartArea } from './duel-tone/ChartArea'
export { default as Building } from './duel-tone/Building'
export { default as Building2 } from './duel-tone/Building2'
export { default as Sheild } from './duel-tone/Sheild'
export { default as Error } from './duel-tone/Error'
export { default as Diamond } from './duel-tone/Diamond'
export { default as Expand } from './duel-tone/Expand'
export { default as Heroicon } from './duel-tone/Heroicon'
export { default as LucideIcon } from './duel-tone/LucideIcon'
export { default as CustomIcon } from './duel-tone/CustomIcon'
export { default as Mail } from './duel-tone/Mail'
export { default as User } from './duel-tone/User'
export { default as Phone } from './duel-tone/Phone'
export { default as Location } from './duel-tone/Location'
export { default as Calender } from './duel-tone/Calendar'
export { default as CalenderCheck } from './duel-tone/CalenderCheck'
export { default as UserPlus } from './duel-tone/UserPlus'
export { default as UserSign } from './duel-tone/UserSign'
export { default as Web } from './duel-tone/Web'
export { default as Mail2 } from './duel-tone/Mail2'
export { default as BlankVector } from './ManVector'
export { default as DashBoard } from './duel-tone/Dashboard'
export { default as Application } from './duel-tone/Application'
export { default as Authentication } from './duel-tone/Authentication'
export { default as Components } from './duel-tone/Components'
export { default as Grid } from './duel-tone/Grid'
export { default as Stacks2 } from './duel-tone/Stacks'
export { default as Pages } from './duel-tone/Pages'
export { default as Chart } from './duel-tone/Chart'
export { default as Map } from './duel-tone/Map'
export { default as SiteLogo } from './duel-tone/Logo'
export { default as Settings } from './duel-tone/Settings'
export { default as Files } from './duel-tone/Files'
export { default as Graph } from './duel-tone/Graph'
export { default as Cart } from './duel-tone/Cart'
export { default as ClipBoard } from './duel-tone/ClipBoard'
export { default as Envelope } from './duel-tone/Envelope'
export { default as Messages } from './duel-tone/Message'
export { default as Monitor } from './duel-tone/Monitor'
export { default as List } from './duel-tone/List'
export { default as ListFill } from './duel-tone/ListFill'
export { default as Calendar } from './duel-tone/Calendar'
export { default as Flag } from './duel-tone/Flag'
export { default as Book } from './duel-tone/Book'
export { default as Note } from './duel-tone/Note'
export { default as Medical } from './duel-tone/Medical'
export { default as ClipBoard2 } from './duel-tone/ClipBoard2'
export { default as Note2 } from './duel-tone/Note2'
export { default as Note3 } from './duel-tone/Note3'
export { default as BarLeft } from './duel-tone/BarLeft'
export { default as BarTop } from './duel-tone/BarTop'
export { default as ChartBar } from './duel-tone/ChartBar'
export { default as PretentionChartLine } from './duel-tone/PretentionChartLine'
export { default as PretentionChartLine2 } from './duel-tone/PretentionChartLine2'
export { default as Google } from './duel-tone/Google'
export { default as Pointer } from './duel-tone/Pointer'
export { default as Map2 } from './duel-tone/Map2'
export { default as MenuBar } from './duel-tone/MenuBar'
export { default as Icons } from './duel-tone/Icons'
export { default as Sun } from './duel-tone/Sun'
export { default as Moon } from './duel-tone/Moon'
export { default as Device } from './duel-tone/Device'

// sidebar icon
export { default as FolderTree } from './home/Foldertree'



